### ISSUE TITLE
not register car

### ISSUE THREAD

**Issue by Deniel00** [Trsak/esx_inventoryhud_trunk#13]
Our players cars not register in to database, and drop this log:

```lua
Error running call reference function for resource esx_inventoryhud_trunk: citizen:/scripting/lua/scheduler.lua:403: @esx_inventoryhud_trunk/server/esx_trunk-sv.lua:216: attempt to index a nil value (local 'blackMoney')
stack traceback:
	@esx_inventoryhud_trunk/server/esx_trunk-sv.lua:216: in upvalue 'ref'
	citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
	[C]: in function 'xpcall'
	citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
	[C]: in function 'coroutine.resume'
	citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
	[C]: in function 'coroutine.resume'
	citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
Error running system event handling function for resource esx_inventoryhud_trunk: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
	citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
	citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
	citizen:/scripting/lua/scheduler.lua:626: in local 'cb'
	@esx_inventoryhud_trunk/server/trunk.lua:106: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
	[C]: in function 'coroutine.resume'
	citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
```

**Comment by Deniel00** [comment]
Scripts said it today:
```lua
[ERROR] [MySQL] [esx_inventoryhud_trunk] An error happens on MySQL for query "INSERT INTO trunk_inventory(plate,data,owned) VALUES ('HOU 662 ','{}',false)": ER_DUP_ENTRY: Duplicate entry 'HOU 662 ' for key 'plate'
[91mError: (node:16234) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
    at process.<anonymous> (internal/process/promises.js:27:25)
    at <anonymous>
    at Query.db.query (mysql-async.js:5152:7)
    at Query.<anonymous> (mysql-async.js:1117:10)
    at Query._callback (mysql-async.js:1083:16)
    at Query.Sequence.end (mysql-async.js:275:24)
    at Query.ErrorPacket (mysql-async.js:2237:8)
    at Protocol._parsePacket (mysql-async.js:6326:23)
    at Parser._parsePacket (mysql-async.js:6937:10)
    at Parser.write (mysql-async.js:6547:10)[0m
[91mError: (node:16234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)[0m
[91mError: (node:16234) UnhandledPromiseRejectionWarning: Error: ER_DUP_ENTRY: Duplicate entry 'HOU 662 ' for key 'plate'
    at Query.Sequence._packetToError (mysql-async.js:239:14)
    at Query.ErrorPacket (mysql-async.js:2224:18)
    at Protocol._parsePacket (mysql-async.js:6326:23)
    at Parser._parsePacket (mysql-async.js:6937:10)
    at Parser.write (mysql-async.js:6547:10)
    at Protocol.write (mysql-async.js:6073:16)
    at Socket.<anonymous> (mysql-async.js:683:28)
    at Socket.<anonymous> (mysql-async.js:1117:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Pool.query (mysql-async.js:4904:23)
    at Promise (mysql-async.js:5149:8)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:5146:24)
    at Object.global.exports [as callback] (mysql-async.js:5164:3)
    at citizen:/scripting/v8/main.js:96:41[0m
[91mError: (node:16234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)[0m
```

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
